package social_feeds_dao

import (
	"testing"
)

// var (
// 	rootPostID = PostID(0)
// 	postID1    = PostID(1)
// 	feedID1    = FeedID(1)
// 	cat1       = uint64(1)
// 	cat2       = uint64(2)
// 	user       = testutils.TestAddress("user")
// 	filter_all = []uint64{}
// )

func Test(t *testing.T) {
	// Prepare feed, post
	// feedID := CreateFeed("teritori")
	// feed := mustGetFeed(feedID)

	// // Create Posts
	// postToBanID := CreatePost(feed.id, rootPostID, cat1, "metadata1")
	// CreatePost(feed.id, rootPostID, cat1, "metadata2")

	// Make proposal
	// Propose(0, "Ban Post "+postToBanID.String(), "We want to delete this post", "")
}
